leapdao/leapdao-website

.gitignore
.gitmodules
.travis.yml
gulpfile.js
index.html
main.css
src/blog/template/post-index.html
src/blog/template/post.html
src/page-template.html

Use https://github.com/leapdao/leapdao-bounties repo as a submodule and build pages from its' content

Bounties and CoC pages

---

src/blog/content/Plasma-Mainnet-Launched.md

add bridge call to action

---

main.css
src/blog/content/Ethereum-Foundation-grant-for-Plasma-Leap.md
src/blog/content/Plasma-Mainnet-Launched.md
src/blog/content/Plasma-Roadmap.md
src/blog/content/Plasma-Testnet-Launched.md
src/blog/content/Smart-Contracts-on-Plasma.md

Preview: https://test.leapdao.org/blog

Improved blog styles

---

main.js

Another way to show off :-)
Very unnecessary, but since we render blobby with canvas, we can do it 🤷‍♂️

Dynamic favicon

---

src/blog/content/ethereal-virtual-hackathon-results.md

fix: Dungeron Riches github link yields 404

---

index.html
main.css

resolves https://github.com/leapdao/leapdao-website/issues/51

new Landing

---

index.html

Reasoning:
- too noisy for the clean(ish) design
- not adding any value

feat: remove emoji from headers

---

whitepaper/index.html

https://leapdao.org/whitepaper/ → whitepaper

feat: poor-man shortlink for whitepaper. 

---

index.html
main.js

refactor: move presentation parts for metrics code to html/css

---

index.html
main.css

Otherwise it may be misleading, as PoS is not available on Leap Network yet.
I'm not happy with proposed look and feel, appreciate help

feat: show Validate section as "Not available"

---

earn.html

Link to Apply for a grant

---

src/blog/content/mainnet-upgrade-1.2.0.md

review for https://github.com/leapdao/leapdao-website/issues/99

minor things

---

scripts/bounties.js

Allows to specify shares in DAI, like:
```
worker: @troggy / 100 DAI
```
See https://github.com/leapdao/integration-tests/issues/52

feat: parse DAI shares for bounties as well

---

index.html
src/blog/template/post-index.html
src/blog/template/post.html

Revert "feat: digital climate strike (#120)"
This reverts commit 675f9480b45ba45ac08fdf6252dbf5ea71a0f268.

strike is over, back to work

---

src/blog/content/cas.md

Resolves https://github.com/leapdao/leapdao-website/issues/106

blog: CAS in Leap Network

---

src/routes/_index/Stats.svelte

Integrated API to fetch monthly active UTXOs

---

src/posts/Slaps-for-the-Chains.md
src/routes/blog/[slug].svelte

- move slaps scripts into template
- and make it defer to keep execution order

Fix slaps video

---

.travis.yml
scripts/deploy-prod.sh
scripts/deploy-test.sh

feat(ci): generate robots.txt for test.leapdao.org

---

src/posts/mainnet-shutdown.md

fix: year of mainnet shutdown post

---

src/posts/mainnet-shutdown.md
src/posts/quadratic-voting.md
src/server.js

preview not work.
this pr could fix it 😁

fixed preview

---

src/posts/Ethereal-Virtual-Hackathon.md
src/posts/Planet-A-ccc-ethberlin-recap.md
src/posts/Plasma-Mainnet-Launched.md
src/posts/Plasma-Testnet-Launched.md
src/posts/Popup-Economy-at-Blocksplit.md
src/posts/Requiem-for-Testnet-Zeta.md
src/posts/Rights-Management-Onchain-Cannes-Film.md
src/posts/Slaps-for-the-Chains.md
src/posts/SunDAI-power-Blocksplit-2019.md
src/posts/cas.md
src/posts/ethereal-virtual-hackathon-results.md
src/posts/mainnet-postmortem.md
src/posts/mainnet-revamp.md
src/posts/prime-casino.md
src/routes/blog/[slug].svelte
src/routes/blog/index.svelte

Please remember the [Contributing Guidelines](https://github.com/leapdao/meta/blob/master/CONTRIBUTION.md) :heart:
- tries to address fixes concerning the bug with metadata. 
Closes

feat: redoing 

---

unpin.js

Fixes: #172 
Description: Adds catch statement on for handling promise rejection and showing users the error incurred during the build.
@Clearwood please review.

fix: Catch error on unpin step of build gracefully
